### ISSUE TITLE
discord invite link doesn't work

### ISSUE THREAD

**Issue by d834256** [ddelnano/packer-plugin-xenserver#108]
The discord invite link in the README seems to have expired.

**Comment by ddelnano** [comment]
The link works for me when loaded in an incognito browser window.

<img width="1174" alt="Screenshot 2023-12-16 at 12 46 08 PM" src="https://github.com/ddelnano/packer-plugin-xenserver/assets/5855593/8f81dbf0-39a7-4895-b076-c567e2b857c7">

Can you provide a screenshot or more detailed description of what you are seeing?
