### ISSUE TITLE
[ISO-Builder] Cleanup fails on Step: Wait for VM's IP to become known to us.

### ISSUE THREAD

**Issue by dsko1234** [ddelnano/packer-plugin-xenserver#11]
if a build is aborted in the 
==> xenserver-iso.centos: Step: Wait for VM's IP to become known to us.
stage, packer terminates without cleaning up the vm

To reproduce:
start one ofh the example builds,
send a SIGTERM (ctrl+c) once 
==> xenserver-iso.cloudinit-base: Step: Wait for VM's IP to become known to us. 
apears

**Comment by ddelnano** [comment]
Thanks for this issue. This should be an easy fix. Once #10 is figured out I'll take a look at addressing this.

**Comment by ddelnano** [comment]
@dsko1234 this will be released in v0.3.2
