### ISSUE TITLE
Allow users to install the packer plugin with `packer init`

### ISSUE THREAD

**Issue by ddelnano** [ddelnano/packer-plugin-xenserver#14]
Now that we've upgraded to the packer-plugin-sdk, we should be able to allow users to install it with `packer init`. I had difficulty getting this to work during #13 but this should be the supported way for installing the plugin in recent versions of packer.

**Comment by dsko1234** [comment]
I have done some tests:
with a known good plugin for comparison [upcloud](https://github.com/UpCloudLtd/packer-plugin-upcloud/releases)
```hcl

packer {
  required_plugins {
   xenserver= {
      version = "= v0.3.0-dev9"
      source = "github.com/ddelnano/xenserver"
    }
   upcloud = {
      version = "= v1.0.0"
      source = "github.com/UpCloudLtd/upcloud"
    }
  }
}
```
`PACKER_LOG=1 packer init centos8-init.pkr.hcl`
produces [packer-init-log.txt](https://github.com/ddelnano/packer-plugin-xenserver/files/6133370/packer-
init-log.txt)

Looking at the logs, packer ist unable to match the right plugin executable for the provided version.
```
2021/03/12 23:27:06 [TRACE] Ignoring remote binary packer-plugin-xenserver_v0.3.0-dev9_x5.0_linux_amd64.zip, wrong version, expected v0.3.0-dev9 

```
comparing to the known good, the only real difference is '-dev9'
```
packer-plugin-upcloud  _v1.0.0     _x5.0_linux_arm64.zip
packer-plugin-xenserver_v0.3.0-dev9_x5.0_linux_amd64.zip
```

Could you maybe have Github actions build the 'v0.3.0' tag for further testing?

**Comment by dsko1234** [comment]
If one populates the ~/packer.d/plugins dir manually, packer uses the plugin without complaining

```
└── github.com
    └── ddelnano
        └── xenserver
            ├── packer-plugin-xenserver_v0.3.0-dev9_x5.0_linux_arm64
            └── packer-plugin-xenserver_v0.3.0-dev9_x5.0_linux_arm64_SHA256SUM
```

**Comment by dsko1234** [comment]
If one manually populates the plugins dir,
packer still errors with 
packer validate
`Error: no plugin installed for github.com/ddelnano/xenserver = v0.3.0-dev9`
packer init
`could not find a local nor a remote checksum for plugin "github.com/ddelnano/xenserver" "= v0.3.0-dev9"`
it looks as tho it doesnt like the '-dev9' designation

**Comment by ddelnano** [comment]
It doesn't seem to like the v0.3.0 release I made. I updated the "ignoring remote binary" log message and recompiled packer to see why it's not matching the file correctly and see that the file seems to be missing the 'v' prefix

```
2021/03/12 17:05:11 [DEBUG] github-getter: getting "https://github.com/ddelnano/packer-plugin-xenserver/releases/download/v0.3.0/packer-plugin-xenserver_v0.3.0_SHA256SUMS"
2021/03/12 17:05:11 [TRACE] Ignoring remote binary packer-plugin-xenserver_v0.3.0_x5.0_freebsd_arm.zip, wrong version: '0.3.0' does not match expected v0.3.0
2021/03/12 17:05:11 [TRACE] Ignoring remote binary packer-plugin-xenserver_v0.3.0_x5.0_freebsd_arm64.zip, wrong version: '0.3.0' does not match expected v0.3.0
2021/03/12 17:05:11 [TRACE] Ignoring remote binary packer-plugin-xenserver_v0.3.0_x5.0_linux_arm64.zip, wrong version: '0.3.0' does not match expected v0.3.0
2021/03/12 17:05:11 [TRACE] Ignoring remote binary packer-plugin-xenserver_v0.3.0_x5.0_linux_arm.zip, wrong version: '0.3.0' does not match expected v0.3.0
2021/03/12 17:05:11 [TRACE] Ignoring remote binary packer-plugin-xenserver_v0.3.0_x5.0_linux_386.zip, wrong version: '0.3.0' does not match expected v0.3.0
2021/03/12 17:05:11 [TRACE] Ignoring remote binary packer-plugin-xenserver_v0.3.0_x5.0_darwin_amd64.zip, wrong version: '0.3.0' does not match expected v0.3.0
2021/03/12 17:05:11 [TRACE] Ignoring remote binary packer-plugin-xenserver_v0.3.0_x5.0_darwin_arm64.zip, wrong version: '0.3.0' does not match expected v0.3.0
2021/03/12 17:05:11 [TRACE] Ignoring remote binary packer-plugin-xenserver_v0.3.0_x5.0_freebsd_amd64.zip, wrong version: '0.3.0' does not match expected v0.3.0
2021/03/12 17:05:11 [TRACE] Ignoring remote binary packer-plugin-xenserver_v0.3.0_x5.0_freebsd_386.zip, wrong version: '0.3.0' does not match expected v0.3.0
2021/03/12 17:05:11 [TRACE] Ignoring remote binary packer-plugin-xenserver_v0.3.0_x5.0_windows_386.zip, wrong version: '0.3.0' does not match expected v0.3.0
2021/03/12 17:05:11 [TRACE] Ignoring remote binary packer-plugin-xenserver_v0.3.0_x5.0_windows_amd64.zip, wrong version: '0.3.0' does not match expected v0.3.0
2021/03/12 17:05:11 [TRACE] Ignoring remote binary packer-plugin-xenserver_v0.3.0_x5.0_linux_amd64.zip, wrong version: '0.3.0' does not match expected v0.3.0
could not find a local nor a remote checksum for plugin "github.com/ddelnano/xenserver" "= v0.3.0"

```

**Comment by ddelnano** [comment]
Turns out this was a packer bug :smile: 

https://github.com/hashicorp/packer/pull/10760 fixes this issue. Any packer plugin whose name contains a "v" (such as xenser**v**er) will experience this problem

**Comment by ddelnano** [comment]
https://github.com/hashicorp/packer/pull/10760 has been merged and will be released in packer 1.7.1. Once that version is released, I will close this.

**Comment by ddelnano** [comment]
This now works on packer 1.7.1!

```
ddelnano@ddelnano-desktop:~/go/src/github.com/xenserver/packer-builder-xenserver$ cat file.pkr.hcl
packer {
  required_plugins {
   xenserver= {
      version = ">= v0.3.0"
      source = "github.com/ddelnano/xenserver"
    }
  }
}

ddelnano@ddelnano-desktop:~/go/src/github.com/xenserver/packer-builder-xenserver$ packer1.7.1 init file.pkr.hcl
Installed plugin github.com/ddelnano/xenserver v0.3.2 in "/home/ddelnano/.packer.d/plugins/github.com/ddelnano/xenserver/packer-plugin-xenserver_v0.3.2_x5.0_linux_amd64"
```

**Comment by ddelnano** [comment]
Actually I closed this too soon. The documentation needs to be updated first.

**Comment by ddelnano** [comment]
In addition to updating the documentation to use `packer init`, we need to migrate all the json templates to hcl. That work is being done in #7.

**Comment by ddelnano** [comment]
Now that #7 is complete and I've updated the documentation (6005f12d3dafb94b6ad02bc9f3352a90f203f86f), this is complete.
