### ISSUE TITLE
iso_name description missing from xenserver-iso.html.markdown

### ISSUE THREAD

**Issue by tschilb252** [ddelnano/packer-plugin-xenserver#21]
The https://github.com/ddelnano/packer-plugin-xenserver/blob/master/docs/builders/xenserver-iso.html.markdown page does not have any information on the "iso_name" property.

**Comment by Shackelford-Arden** [comment]
@tschilb252 Is this what you are referring to?

https://github.com/ddelnano/packer-plugin-xenserver/blob/main/docs/builders/iso/xenserver-iso.html.markdown?plain=1#L136-L137

**Comment by tschilb252** [comment]
Wow this is an old one. I believe we got the issue fixed with an acceptable work around. Thanks for your response!

V/r

Timothy H. Schilbach, PhD
CISSP, CCSP, OSCP, OSCE
Book a meeting with me here<https://calendly.com/tschilbach/teams-meeting?month=2023-06>!
CEO | Penacity, LLC | AboutWeb, LLC | 7030 Dorsey Rd, Suite 104, Hanover, MD 21076<https://maps.google.com/?q=8489+Rugby+Rd+%23335,+Pasadena,+MD+21122&entry=gmail&source=g>
Mobile: (703) 586-0407<tel:(703)+586-0407> | Office: (443) 837-9550<tel:(443)%20837-9550> x100 | Email: ***@***.******@***.***>
***@***.******@***.******@***.***

**Comment by Shackelford-Arden** [comment]
Just trying to learn more about the project, figured I'd comment and check :)

I can't close issues, so if you're good and wouldn't mind closing the issue, that'd be awesome!

**Comment by tschilb252** [comment]
Arden,

  Did you have a specific issue? I can assist with a work around if needed.

V/r

Timothy H. Schilbach, PhD
CISSP, CCSP, OSCP, OSCE
Book a meeting with me here<https://calendly.com/tschilbach/teams-meeting?month=2023-06>!
CEO | Penacity, LLC | AboutWeb, LLC | 7030 Dorsey Rd, Suite 104, Hanover, MD 21076<https://maps.google.com/?q=8489+Rugby+Rd+%23335,+Pasadena,+MD+21122&entry=gmail&source=g>
Mobile: (703) 586-0407<tel:(703)+586-0407> | Office: (443) 837-9550<tel:(443)%20837-9550> x100 | Email: ***@***.******@***.***>
***@***.******@***.******@***.***

**Comment by Shackelford-Arden** [comment]
No, I'm all set. Thanks for checking though!

I'm just trying to learn more about the project by going through open issues.
