### ISSUE TITLE
Please create a release based on tag v0.4.0

### ISSUE THREAD

**Issue by olegbukatchuk** [ddelnano/packer-plugin-xenserver#34]
Hey! Please create a release based on https://github.com/ddelnano/packer-plugin-xenserver/releases/tag/v0.4.0
so that it can be used in code, something like this:
packer {
 required_plugins {
   xenserver={
     version = "v0.4.0"
     source = "github.com/ddelnano/xenserver"
    }
  }
}

**Comment by ddelnano** [comment]
I had created the release weeks ago but it was set to a draft 🤦‍♂️. It should be available now ([v0.4.0](https://github.com/ddelnano/packer-plugin-xenserver/releases/tag/v0.4.0)).
