### ISSUE TITLE
Update to packer-sdc command for validating plugin compatibility

### ISSUE THREAD

**Issue by nywilken** [ddelnano/packer-plugin-xenserver#35]
👋 Fellow Packer maintainer here,  reaching out to inform you about an upcoming breaking change that will affect your goreleaser release pipeline. In Packer 1.8.0 we will remove the [`packer-plugin-check`](github.com/hashicorp/packer/cmd/packer-plugins-check) command in Packer core in favor of the [`packer-sdc plugin-check`](https://github.com/hashicorp/packer-plugin-sdk/cmd/packer-sdc) command from the [Packer Plugin SDK](https://github.com/hashicorp/packer-plugin-sdk/tree/main/cmd/packer-sdc). So calling `go install github.com/hashicorp/packer/cmd/packer-plugins-check@latest` will result in an error. 

To avoid potential issues I recommend either pinning the `packer-plugins-check` command to the current version of Packer until you can move to the `packer-sdc` command

`go install github.com/hashicorp/packer/cmd/packer-plugins-check@v1.7.10` 

Or you can update your release configuration to use the `packer-sdc` command, which is the preferred long-term solution. 

I'v provided a link to the updates that were made to the Packer Plugin Scaffolding for using the `packer-sdc` command [here](https://github.com/hashicorp/packer-plugin-scaffolding/pull/63/files#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689)

Please let me know if you have any questions.

**Comment by nywilken** [comment]
Hi @ddelnano, thanks for following up. I saw the reference to the `packer-plugins-check` command in the project [.goreleaser.yml](https://github.com/ddelnano/packer-plugin-xenserver/blob/f4a161e8067cd127e250c1631518f86611e7aa40/.goreleaser.yml#L21) file. So thought that it was being used. 

> Am I correct in thinking that this won't cause any breakage for this plugin? 
If you are not using that [.goreleaser.yml](https://github.com/ddelnano/packer-plugin-xenserver/blob/f4a161e8067cd127e250c1631518f86611e7aa40/.goreleaser.yml#L21) config for your releases than you can ignore this request and close the issue. Sorry I did not go too deep into your release process. Otherwise, I would expect your plugin release to fail once Packer 1.8.0 is released. You can also remove the check if you would like to revisit at a later time.

**Comment by ddelnano** [comment]
ah, that goreleaser file at the root of the repo was the one I used to publish locally before I set up GitHub actions. That file can be remove at this time and thanks for bringing this up!

**Comment by ddelnano** [comment]
This was completed in https://github.com/ddelnano/packer-plugin-xenserver/commit/ac90dec7ea1e13d84d7c559de39a6de2f6d06d85
