### ISSUE TITLE
When using the Packer HCL required plugins stanza getting an error where the 256SUM is not found

### ISSUE THREAD

**Issue by tschilb252** [ddelnano/packer-plugin-xenserver#36]
#### packer.hcl file ####
packer {
  required_plugins {
    xenserver= {
      version = ">= v0.4.0"
      source = "github.com/ddelnano/xenserver"
    }
  }
}

#### RUNTIME ERROR ####
could not get sha256 checksum file for github.com/ddelnano/xenserver version 1.0.0. Is the file present on the release and correctly named ? GET https://github.com/ddelnano/packer-plugin-xenserver/releases/download/v1.0.0/packer-plugin-xenserver_v1.0.0_SHA256SUMS: 404  []

building image...
Error: no plugin installed for github.com/ddelnano/xenserver >= v0.4.0

**Comment by tschilb252** [comment]
I was able to implement a workaround pinning at the v0.4.0 or the v0.3.2 version.  Still need to fix the root version being whatever the latest release is vs 1.0

packer {
  required_plugins {
    xenserver = {
      version = "= v0.4.0"
      source = "github.com/ddelnano/xenserver"
    }
  }
}

**Comment by ddelnano** [comment]
Hey @tschilb252, thanks for making this bug report.

I am able to reproduce the behavior, but I'm surprised since I don't see any releases or tags that match v1.0.0. I ran packer with `PACKER_LOG=debug` set to see if I could determine where that was being pullet from and saw the following:

```
2022/03/07 22:29:49 [INFO] Packer version: 1.7.0 [go1.15.8 linux amd64]
2022/03/07 22:29:49 [TRACE] discovering plugins in /usr/local/bin
2022/03/07 22:29:49 [TRACE] discovering plugins in /home/ddelnano/.packer.d/plugins
2022/03/07 22:29:49 [TRACE] discovering plugins in .
2022/03/07 22:29:49 [DEBUG] Discovered plugin: xenserver = /home/ddelnano/go/src/github.com/xenserver/packer-plugin-xenserver/packer-builder-xenserver
2022/03/07 22:29:49 [INFO] using external builders: [xenserver]
2022/03/07 22:29:49 [DEBUG] Discovered plugin: xenserver = /home/ddelnano/go/src/github.com/xenserver/packer-plugin-xenserver/packer-plugin-xenserver
2022/03/07 22:29:49 [INFO] found external [iso xva] builders from xenserver plugin
2022/03/07 22:29:49 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2022/03/07 22:29:49 [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/ddelnano/.packerconfig
2022/03/07 22:29:49 [WARN] Config file doesn't exist: /home/ddelnano/.packerconfig
2022/03/07 22:29:49 [INFO] Setting cache directory: /home/ddelnano/go/src/github.com/xenserver/packer-plugin-xenserver/packer_cache
2022/03/07 22:29:49 [TRACE] validateValue: not active for remote_password, so skipping
2022/03/07 22:29:49 [TRACE] validateValue: not active for remote_username, so skipping
2022/03/07 22:29:49 [TRACE] validateValue: not active for sr_iso_name, so skipping
2022/03/07 22:29:49 [TRACE] validateValue: not active for sr_name, so skipping
2022/03/07 22:29:49 [TRACE] validateValue: not active for remote_host, so skipping
2022/03/07 22:29:49 [TRACE] init: plugingetter.ListInstallationsOptions{FromFolders:[]string{"/usr/local/bin/packer1.7", ".", "/home/ddelnano/.packer.d/plugins"}, BinaryInstallationOptions:plugingetter.BinaryInstallationOptions{APIVersionMajor:"5", APIVersionMinor:"0", OS:"linux", ARCH:"amd64", Ext:"", Checksummers:[]plugingetter.Checksummer{plugingetter.Checksummer{Type:"sha256", Hash:(*sha256.digest)(0xc000080100)}}}}
2022/03/07 22:29:49 [TRACE] listing potential installations for "github.com/ddelnano/xenserver" that match ">= v0.3.2". plugingetter.ListInstallationsOptions{FromFolders:[]string{"/usr/local/bin/packer1.7", ".", "/home/ddelnano/.packer.d/plugins"}, BinaryInstallationOptions:plugingetter.BinaryInstallationOptions{APIVersionMajor:"5", APIVersionMinor:"0", OS:"linux", ARCH:"amd64", Ext:"", Checksummers:[]plugingetter.Checksummer{plugingetter.Checksummer{Type:"sha256", Hash:(*sha256.digest)(0xc000080100)}}}}
2022/03/07 22:29:49 [TRACE] for plugin github.com/ddelnano/xenserver found 0 matching installation(s)
2022/03/07 22:29:49 [TRACE] getting available versions for the github.com/ddelnano/xenserver plugin
2022/03/07 22:29:49 [DEBUG] github-getter: getting "https://api.github.com/repos/ddelnano/packer-plugin-xenserver/git/matching-refs/tags"
2022/03/07 22:29:49 [DEBUG] will try to install: [1.0.0 0.4.0 0.3.2]
2022/03/07 22:29:49 [TRACE] fetching checksums file for the "1.0.0" version of the github.com/ddelnano/xenserver plugin in "/home/ddelnano/.packer.d/plugins/github.com/ddelnano/xenserver"...
2022/03/07 22:29:49 [DEBUG] github-getter: getting "https://github.com/ddelnano/packer-plugin-xenserver/releases/download/v1.0.0/packer-plugin-xenserver_v1.0.0_SHA256SUMS"
2022/03/07 22:29:49 [TRACE] could not get sha256 checksum file for github.com/ddelnano/xenserver version 1.0.0. Is the file present on the release and correctly named ? GET https://github.com/ddelnano/packer-plugin-xenserver/releases/download/v1.0.0/packer-plugin-xenserver_v1.0.0_SHA256SUMS: 404  []
2022/03/07 22:29:49 [INFO] (telemetry) Finalizing.
could not get sha256 checksum file for github.com/ddelnano/xenserver version 1.0.0. Is the file present on the release and correctly named ? GET https://github.com/ddelnano/packer-plugin-xenserver/releases/download/v1.0.0/packer-plugin-xenserver_v1.0.0_SHA256SUMS: 404  []
2022/03/07 22:29:49 waiting for all plugin processes to complete...

```

So it does appear to be looking for a 1.0.0 release. I checked the releases from URL specified in the logs above (https://api.github.com/repos/ddelnano/packer-plugin-xenserver/git/matching-refs/tags) and found a 1.0 release but nothing that matched 1.0.0.

I took a look at the packer source code and realized that it is padding [all releases](https://github.com/hashicorp/packer/blob/d82135d4f5587531b0fe0c6118b1fa064d17d77f/packer/plugin-getter/plugins.go#L140) to [3 digits](https://github.com/hashicorp/go-version/blob/45914bea74f309ae20bfd8fe93676d72cd18ecff/version.go#L77-L78). So that 1.0 release, which is a tag from before this project was forked, was being transformed into 1.0.0.

I've deleted that tag and verified that issue no longer occurs. Please reopen the issue if you are still experiencing a problem!

**Comment by tschilb252** [comment]
Thanks for the prompt response and fix.  I was also able to work around the issue with setting the implicit version vs. being lazy and state “this or older”.

Do you have a link we can donate to assist with the burdens of maintenance?

V/r

Timothy H. Schilbach, PhD
CISSP, CCSP, OSCP, OSCE
CMMC Registered Practitioner
CEO | Penacity, LLC | AboutWeb, LLC | 7030 Dorsey Rd, Suite 104, Hanover, MD 21076<https://us-east-2.protection.sophos.com/?d=outlook.com&u=aHR0cHM6Ly9uYW0xMi5zYWZlbGlua3MucHJvdGVjdGlvbi5vdXRsb29rLmNvbS8_dXJsPWh0dHBzJTNBJTJGJTJGbWFwcy5nb29nbGUuY29tJTJGJTNGcSUzRDg0ODklMkJSdWdieSUyQlJkJTJCJTI1MjMzMzUlMkMlMkJQYXNhZGVuYSUyQyUyQk1EJTJCMjExMjIlMjZlbnRyeSUzRGdtYWlsJTI2c291cmNlJTNEZyZkYXRhPTAyJTdDMDElN0NlbWVkZSU0MGVlY29tcHV0aW5nLmNvbSU3Q2I5ZGE1ZWI2NzM0MDQ2YWVmNjYzMDhkN2ZjMjgzNzVjJTdDMjY1ZGU0OGI4ZDc0NDU3MGFhNTU4MjY2Zjc2ZDY3MTklN0MwJTdDMCU3QzYzNzI1NTEyMTk5ODQ3NjI0OCZzZGF0YT1RTGNHWkFsWFE1R1hDUXElMkJOd0ZlbHBSR25MV1RIbm1UUmZFZUtTRlNESjglM0QmcmVzZXJ2ZWQ9MA==&e=dHNjaGlsYmFjaEBwZW5hY2l0eS51cw==&h=bc6dc7d52ad24c3aa3a13a718903194a&t=eCsxNGNZWEFLbVoyZWsyTGtSa2I4eERCYy9GOGRTMTNzd2lFVzNka3hJZz0=>
Mobile: (703) 586-0407<tel:(703)+586-0407> | Office: (443) 837-9550<tel:(443)%20837-9550> x100 | Email: ***@***.******@***.***>
***@***.******@***.*** ***@***.***

**Comment by ddelnano** [comment]
@tschilb252 no problem! I just added a [buymeacoffee](https://www.buymeacoffee.com/ddelnano) link to the README of the project if you are interested in supporting my work on the project
