### ISSUE TITLE
Release v0.5.0 assets are not compatible with packer 1.7

### ISSUE THREAD

**Issue by mboutet** [ddelnano/packer-plugin-xenserver#40]
As a result, Packer is unable to download the plugin.

For example, release v0.4.0 contains the adequate assets.

**Comment by ddelnano** [comment]
The CI job that releases the binaries is broken and unfortunately I didn't have time to fix it the day I realized this. There is something that needs to be migrated #35, which I'll try to look at soon.

**Comment by ddelnano** [comment]
@mboutet I've released v0.5.0 which includes a newer packer-plugin-sdk. This seems to have broken packer 1.7 from being able to install the provider. The release notes of the packer-plugin-sdk didn't mention any obvious breaking changes

<img width="1525" alt="Screen Shot 2022-06-12 at 4 58 04 PM" src="https://user-images.githubusercontent.com/5855593/173258878-a9cba968-10f1-454a-9299-d90496c6fb3b.png">

I need to spend more time looking into that, but hopefully upgrading to packer 1.8 will work until I figure that out.

**Comment by ddelnano** [comment]
packer 1.8 doesn't have an issue with the latest releases. Since this is the latest release of packer, I'm going to close this issue.
