### ISSUE TITLE
Xenserver-iso no longer working with packer 1.7 

### ISSUE THREAD

**Issue by dsko1234** [ddelnano/packer-plugin-xenserver#9]
With the new packer version 1.7 came some changes to the plugin infrastucture.
attempting to use the xenserver-iso builder with packer 1.7 results in this error.
```
Error: Failed to load source type
The protocol of this plugin (protocol version 4 and lower) was deprecated,
please use a newer version of this plugin.Or use an older version of Packer (pre
1.7) with this plugin.
```
looking  at
https://www.packer.io/docs/plugins#installing-plugins
plugins are now beeing declared directly in the packer files.
and the `packer-builder-xenserver-iso` naming sheme is beeing deprecated in favor of something like
`packer-plugin-xenserver` as a multi-plugin binary

**Comment by dsko1234** [comment]
More information on what change:
https://www.packer.io/guides/1.7-plugin-upgrade

**Comment by ddelnano** [comment]
Sorry not sure how I missed all these issues being created. I never received an email or notification for these.
